version: '3.8'

services:
  VSTU_Project:
    image: jimbanan/vstu:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/VstuProject
    ports:
      - "8190:8190"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=VstuProject
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
