spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/VstuProject
    username: postgres
    password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.mail.ru
    port: 465
    username: vgtuevents@mail.ru
    password: kiEj5dJcNWq7a81LCjkj
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.mail.ru
      mail.debug: true

server:
  port: 8190

upload_dir: target/classes/static/images/images_for_courses/